### ISSUE TITLE
Documentation for the SKOS add-on

### ISSUE THREAD

**Issue by bquinn** [iptc/sport-schema#152]
Create a new page in the /tools/ folder ("Working with Sport Schema") that explains the SKOS add-on and how it can be used in MarkLogic etc.

**Comment by bquinn** [comment]
@awanczowski are you able to help with this?

**Comment by awanczowski** [comment]
@bquinn yes I can help with this. I'll get back to you shortly.

**Comment by bquinn** [comment]
Fixed by #158
