### ISSUE TITLE
add  resultEffect and resultEffectTarget to ontology, remove outcomeResult

### ISSUE THREAD

**Issue by bquinn** [iptc/sport-schema#154]
Add
SPORT:infractionLevel (called penalty-level in SportsML)
sport:infractionType (called penalty-type in SportsML)
corestatistics:outcome-result
corestatistics:rating (on CompetitorParticipation?)

Also:
Remove  goalMouthZone, pitchZone, relatedAssist, tbd, personReplacingPosition from sample data - we might add them to the ontology in the future.
Change "length" on actions to be "distance"

Also need to finish #113 - hopefully that will help with this work!

**Comment by bquinn** [comment]
As discussed last week, we had "penaltyLevel" and "penaltyType" in the ontology. So I have now changed these to be "infractionLevel" and "infractionType".

For "outcome-result", we have "resultEffect" defined in the core statistics ontology.

Actually I noticed that in SportsML itself, we have "outcome-result" defined in "base2StatsComplexType" referring to outcomeResultComplexType. This type allows common and coverage attributes and has attributes type, key and comment.

The one that indicates what happens as a consequence of the result seems to be resultEffect, which is already defined in the corestatistics ontology.

**Comment by bquinn** [comment]
And spstat:rating already exists in the corestatistics ontology.

**Comment by bquinn** [comment]
Just to be clear for the future: we aren't porting "outcome-result" element from SportsML, we are defining "resultEffect" in the ontology.

**Comment by bquinn** [comment]
Sports Schema | SportsML equivalent | Definition/description | notes
| --- | --- | --- | ---
eventOutcome: 
eventOutcomeType: 
outcomeResult: | `outcome-result` | A report on the result, if any, from the event etc | usually applies to a season
outcomeResultType | `outcome-result@type` | The type of outcome result. Can be things like relegation, promotion and qualification | 
resultEffect: | `@result-effect` | Describes the effect that the result of the event or rank changing has had on the team. Example: Whether or not a team has qualified for the playoffs, or has been promoted or demoted to a different division. SportsML vocab uri: http://cv.iptc.org/newscodes/spresulteffect/

**Comment by pauljkelly** [comment]
Current thoughts: We ignore outcome-result and outcome-result@type in the SportsML (this was a bit of hack in order to specify the competition to which a team was promoted or relegated.) It's actually unclear what this element does since it has few attributes and something like @result-effect would sit well among the attributes of "outcome-totals". It could be accompanied with something like @result-effect-key for the future competition or phase.

In Sports Schema could we then just use resultEffect and resultEffectKey as applied to either an event, phase or competition?

**Comment by bquinn** [comment]
we can make resultEffect apply to (have a rdfs:domain of) ParticipatableThing , which makes it available to be used on both Competition and Event.

we also need to add a new property resultEffectTarget to point to the thing qualified for, as discussed elsewhere.

Then we shouldn't need outcomeResult.
