### ISSUE TITLE
penalty levels in soccer matches URI vs string - should all be URIs

### ISSUE THREAD

**Issue by bquinn** [iptc/sport-schema#157]
grep 'penaltyLevel' samples/ttl/*
samples/ttl/soccer-match-01.ttl:        sport:penaltyLevel    <http://cv.iptc.org/newscodes/spsocpenaltylevel/yellow-card> ;
samples/ttl/soccer-match-02.ttl:        sport:penaltyLevel    "yellow-card" ;
samples/ttl/soccer-match-03.ttl:        sport:penaltyLevel    "yellow-card" ;
samples/ttl/soccer-match-03.ttl:        sport:penaltyLevel    "yellow-card" ;
samples/ttl/soccer-match-04.ttl:        sport:penaltyLevel    "yellow-card" ;
samples/ttl/soccer-match-04.ttl:        sport:penaltyLevel    "yellow-card" ;
samples/ttl/soccer-match-04.ttl:        sport:penaltyLevel    "yellow-card" ;
samples/ttl/soccer-match-04.ttl:        sport:penaltyLevel    "yellow-card" ;
samples/ttl/soccer-match-04.ttl:        sport:penaltyLevel    "yellow-card" ;

**Comment by pauljkelly** [comment]
Another one magically already done.
