### ISSUE TITLE
event / subEvent or competition / event for esports?

### ISSUE THREAD

**Issue by bquinn** [iptc/sport-schema#91]
We have one outstanding "double domain" entry in the ontology: we have sport:event on both Action and Event.

This is because in the eSports example, we have some "sub-events" and we are representing them as an Event with sport:event property pointing to Event.

We would like to change this so we can have a clearly defined domain on sport:event in the ontology.

Options:
* Rename the Event -> event -> Event property to be called "subEvent" instead, and add it to the diagram
* Change the Event -> event -> Event relationship to be Event -> competition -> Competition instead. This means that the "heats" are Events but the aggregate "games" are Competitions. Bring it more in line with athletics.
* any other options??

To be discussed on today's call..?

**Comment by pauljkelly** [comment]
Fixed by creating ParticipatableThing
