### ISSUE TITLE
Do we ever need the TeamMembership class, ie the idea of a team being a member of something?

### ISSUE THREAD

**Issue by bquinn** [iptc/sport-schema#94]
We initially created a generic `Membership` class with a subclass `IndividualMembership`, thinking that one day we might need to add `TeamMembership` as another subclass.

But every time we look at a new use case and think we need a `TeamMembership`, we look at it and realise that it would be better handled with a `TeamParticipation`, to link the team with a league, division, conference etc (which are all handled as types of `Competition`s)

So should we just merge `IndividualMembership` and `Membership` to keep the model simpler, and add `TeamMembership` later if and when we discover that we need it?

If so, should we keep the name `IndividualMembership` anyway, just in case we later need `TeamMembership`, or should we just call it `Membership`?

**Comment by pauljkelly** [comment]
Use participation in season to express "membership". We await future compelling user case for TeamMembership
